export const CORE_COMMAND_EVENT = 'com.zhexian.nlash.event.CORE_COMMAND';

export const CORE_RESPONSE_EVENT = 'com.zhexian.nlash.event.CORE_RESPONSE';

export const CORE_PROGRESS_EVENT = 'com.zhexian.nlash.event.CORE_PROGRESS';

export const CORE_CONTROL_VERSION = 1;

export const MAX_CORE_COMMAND_LENGTH = 16 * 1024;

export const MAX_CORE_RESPONSE_LENGTH = 1024 * 1024;

export const MAX_CORE_PROGRESS_LENGTH = 8 * 1024;
