export const VPN_NOTIFICATION_ID = 1001;

export const VPN_NOTIFICATION_LABEL = 'nlash-vpn-status';

export const VPN_NOTIFICATION_PAUSE_EVENT = 'com.zhexian.nlash.event.PAUSE_PROXY';

export const VPN_NOTIFICATION_REFRESH_EVENT = 'com.zhexian.nlash.event.REFRESH_VPN_NOTIFICATION';

export const VPN_NOTIFICATION_TARGET_PARAMETER = 'targetPage';

export const VPN_NOTIFICATION_DASHBOARD_TARGET = 'dashboard';
